[build]
  functions = "netlify/functions"
  publish = "public"
  command = "echo 'No build step required'"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 8888
  command = "echo 'Functions only - no dev server needed'"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/liff-*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
